In [2]:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

The difference is list_ is list datatype and array_list is numpy.ndarray 


In [9]:
print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [13]:
print(type(list_))
print(type(array_list))
print(list_)
print(array_list)

<class 'list'>
<class 'numpy.ndarray'>
['1', '2', '3', '4', '5']
['1' '2' '3' '4' '5']


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [14]:
array_list = np.array(object = list_, dtype = int)

NumPy arrays are much faster and have strict requirements on the homogeneity of the objects  where as python list can contain a mixture of string, numbers, booleans and other objects


In [17]:
print(type(list_))
print(type(array_list))
print(list_)
print(array_list)

<class 'list'>
<class 'numpy.ndarray'>
['1', '2', '3', '4', '5']
[1 2 3 4 5]


In [18]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [22]:
print(np.size(num_list))
print(np.size(num_array))

6
6


In [23]:
print(np.shape(num_list))
print(np.shape(num_array))

(2, 3)
(2, 3)


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [28]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])